version: "2"

services:
  database_manager:
    build: .
    image: pablerass/microservices-database-manager:latest
    ports:
      - "8888:8888"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres